### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by perry-mitchell** [juliuscc/semantic-release-slack-bot#105]
Getting the following error using this library:

```
[4:36:20 PM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError: Cannot read properties of undefined (reading 'name')
    at module.exports (/builds/<snip>/<snip>/<snip>/node_modules/semantic-release-slack-bot/lib/getConfigToUse.js:5:15)
    at module.exports (/builds/<snip>/<snip>/<snip>/node_modules/semantic-release-slack-bot/lib/fail.js:15:23)
    at validator (file:///builds/<snip>/<snip>/<snip>/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///builds/<snip>/<snip>/<snip>/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (file:///builds/<snip>/<snip>/<snip>/node_modules/semantic-release/node_modules/p-reduce/index.js:16:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  pluginName: 'semantic-release-slack-bot'
}
```

My current config:

```
        ["semantic-release-slack-bot", {
            markdownReleaseNotes: true,
            notifyOnSuccess: false,
            notifyOnFail: false,
            packageName: PROJECT_NAME,
            slackName: SLACK_APP_NAME,
            slackIcon: SLACK_APP_ICON,
            slackWebhook: "https://hooks.slack.com/services/<snip>/<snip>/<snip>",
            branchesConfig: [{
                pattern: "feat/test",
                notifyOnSuccess: true,
                notifyOnFail: true
            }]
        }]
```

I'm initiating semantic release using `npx semantic-release`.

Any ideas? I've tried with `slackName`/`slackIcon` and without, same outcome.

**Comment by perry-mitchell** [comment]
Still no luck, after checking different configs. Here's my current entire semantic-release config:

```javascript
const PROJECT_NAME = "Example";
const SLACK_APP_ICON = ":test:";
const SLACK_APP_NAME = "Auto Deploy"

module.exports = {
    branches: [
        // "master",
        {
            name: "master"
        },
        {
            name: "staging",
            channel: "staging",
            prerelease: "r"
        },
        {
            name: "refactor",
            channel: "refactor",
            prerelease: "r"
        }
    ],
    plugins: [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        "@semantic-release/changelog",
        "@semantic-release/npm",
        ["@semantic-release/exec", {
            publishCmd: "npm run set-build"
        }],
        ["@semantic-release/git", {
            assets: [
                "CHANGELOG.md",
                "package.json",
                "package-lock.json",
                "projects/server/source/library/build.ts"
            ],
            message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
        }],
        "@semantic-release/gitlab",
        ["@semantic-release/exec", {
            publishCmd: "npm run deploy"
        }],
        ["semantic-release-slack-bot", {
            markdownReleaseNotes: true,
            notifyOnSuccess: false,
            notifyOnFail: false,
            packageName: PROJECT_NAME,
            slackName: SLACK_APP_NAME,
            slackIcon: SLACK_APP_ICON,
            slackWebhook: "https://hooks.slack.com/services/<snip>/<snip>/<snip>",
            branchesConfig: [{
                pattern: "refactor",
                notifyOnSuccess: true,
                notifyOnFail: true
            }]
        }],
        ["semantic-release-slack-bot", {
            markdownReleaseNotes: true,
            notifyOnSuccess: false,
            notifyOnFail: false,
            packageName: PROJECT_NAME,
            slackWebhook: "https://hooks.slack.com/services/<snip>/<snip>/<snip>",
            branchesConfig: [{
                pattern: "staging",
                notifyOnSuccess: true,
                notifyOnFail: true
            }]
        }],
        ["semantic-release-slack-bot", {
            markdownReleaseNotes: true,
            notifyOnSuccess: false,
            notifyOnFail: false,
            packageName: PROJECT_NAME,
            slackWebhook: "https://hooks.slack.com/services/<snip>/<snip>/<snip>",
            branchesConfig: [{
                pattern: "master",
                notifyOnSuccess: true,
                notifyOnFail: true
            }]
        }],
        ["@saithodev/semantic-release-backmerge", {
            allowSameBranchMerge: false,
            branchName: "staging",
            backmergeStrategy: "merge",
            mergeMode: "theirs",
            message: "chore(release): Back-merge production release [skip ci]"
        }]
    ]
};
```

**Comment by juliuscc** [comment]
This is a known issue with npx #59

I would love a PR fixing this 👍

**Comment by juliuscc** [comment]
Aha that is strange. So it worked when you used v2 but then you upgraded to v4 and it stopped working? Did you also change any config at the same time?

**Comment by perry-mitchell** [comment]
No format stayed the same. I tried a couple of small changes with no effect. Funnily enough after commenting out this library in my config the official git library for semantic release failed with the same error. 

I'm sensing that using npx for semantic release might just be a bad idea 😅

**Comment by juliuscc** [comment]
Hmm that sounds strange. Could you provide a repo with a working branch and a failing branch? Like a minimum reproducible example?

**Comment by perry-mitchell** [comment]
@juliuscc I tried setting up a demo repository to provide such branches, but I'm [getting Git permission errors](https://github.com/perry-mitchell/semantic-release-slack-bot-demo/actions/runs/4509133469/jobs/7938538467) that I can't overcome. Seems that [others](https://github.com/semantic-release/semantic-release/issues/2495) have had this issue as well.

I'm honestly pretty exhausted with this right now so I'll leave it for now. I'll let you know if I get it working another time.
